# syntax = docker/dockerfile:experimental
ARG SPRYKER_PARENT_IMAGE
FROM ${SPRYKER_PARENT_IMAGE} as application-development

ARG APPLICATION_ENV
ENV APPLICATION_ENV=${APPLICATION_ENV}
ARG SPRYKER_DB_ENGINE
ENV SPRYKER_DB_ENGINE=${SPRYKER_DB_ENGINE}
ARG DEPLOYMENT_PATH
ENV SPRYKER_DB_ENGINE=${SPRYKER_DB_ENGINE}

ENV PATH=/data/vendor/bin:$PATH

ARG USER_UID
RUN usermod -u ${USER_UID} spryker && find / -user 1000 -exec chown -h spryker {} \ || true;

COPY ${DEPLOYMENT_PATH}/context/php/conf.d/91-opcache-dev.ini /usr/local/etc/php/conf.d

ARG SPRYKER_PIPELINE
ENV SPRYKER_PIPELINE=${SPRYKER_PIPELINE}
ARG SPRYKER_BUILD_HASH='current'
ENV SPRYKER_BUILD_HASH=${SPRYKER_BUILD_HASH}
ARG SPRYKER_BUILD_STAMP=''
ENV SPRYKER_BUILD_STAMP=${SPRYKER_BUILD_STAMP}

CMD [ "php-fpm", "--nodaemonize" ]
EXPOSE 9000
