unclassified:
    location:
        url: "${JENKINS_URL}"

jenkins:
    projectNamingStrategy:
        roleBasedProjectNamingStrategy:
            forceExistingJobs: false

    securityRealm:
        oic:
            clientId: "${OIDC_CLIENT_ID}"
            clientSecret: "${OIDC_CLIENT_SECRET}"
            userNameField: "email"
            emailFieldName: "email"
            fullNameFieldName: "name"
            groupsFieldName: "groups"
            pkceEnabled: true
            sendScopesInTokenRequest: true
            serverConfiguration:
                wellKnown:
                    wellKnownOpenIDConfigurationUrl: "${OIDC_WELL_KNOWN}"
                    scopesOverride: "openid profile email"

    authorizationStrategy:
        roleBased:
            roles:
                global:
                    - name: "admin"
                      description: "Full administrative access"
                      permissions:
                          - "Overall/Read"
                          - "Overall/Administer"
                      entries:
                          - group: "jenkins-admins"

                    - name: "viewer"
                      description: "Read-only access to view jobs and builds"
                      permissions:
                          - "Overall/Read"
                          - "Job/Read"
                          - "Job/ExtendedRead"
                          - "Job/Discover"
                          - "Run/Read"
                      entries:
                          - group: "jenkins-viewer"

                    - name: "developer"
                      description: "Can build, view, and cancel jobs"
                      permissions:
                          - "Overall/Read"
                          - "Job/Read"
                          - "Job/Build"
                          - "Job/Cancel"
                          - "Run/Read"
                          - "Run/Replay"
                      entries:
                          - group: "jenkins-developer"

                    - name: "bootstrap-config-runner"
                      description: "Service role for CI/CD pipelines to configure jobs-as-code"
                      permissions:
                          - "Overall/Read"
                          - "Job/Read"
                          - "Job/ExtendedRead"
                          - "Job/Discover"
                          - "Job/Create"
                          - "Job/Configure"
                          - "Job/Delete"
                          - "Job/Build"
                      entries:
                          - group: "jenkins-bootstrap-config-runner"
