name: Spryker B2B Marketplace Demo Shop
on:
  - push

env:
  SPRYKER_TESTING_ENABLED: 1
  PROJECT: b2b-demo-marketplace

jobs:
  functional_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform-image: [
          'spryker/php:8.3',
          'spryker/php:8.4'

        ]
        application-store: [ 'DE' ]
        env: [
          'ci.mysql',
        ]
        repo: [
          'https://github.com/spryker-shop/b2b-demo-marketplace.git'
        ]
    name: "Function Tests(Image: ${{ matrix.platform-image }}, Environment: ${{ matrix.env }}, Repo: ${{ matrix.repo }})"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone demo shop
        run: cd ../ && git clone --depth=1 --branch=master ${{ matrix.repo }} demo-shop && cp -R docker-sdk demo-shop

      - name: Provide env variables
        run: |
          export SPRYKER_PLATFORM_IMAGE=${{ matrix.platform-image}}
          export PROGRESS_TYPE=plain
          export SPRYKER_CURRENT_REGION=EU
          export DYNAMIC_STORE_MODE=true

      - name: Run script
        run: |
          cd ../demo-shop
          docker-sdk/sdk boot .github/deploy/deploy.ci.functional.mariadb.yml -v
          docker-sdk/sdk up -t -v
          docker-sdk/sdk testing codecept run -c tests/codeception.ci.functional.yml

  acceptance_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform-image: [
          'spryker/php:8.3',
          'spryker/php:8.4'
        ]
        env: [
          'ci.mysql'
        ]
        repo: [
          'https://github.com/spryker-shop/b2b-demo-marketplace.git'
        ]
    name: "Acceptance Tests(Image: ${{ matrix.platform-image }}, Environment: ${{ matrix.env }}, Repo: ${{ matrix.repo }})"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone demo shop
        run: cd ../ && git clone --depth=1 --branch=master ${{ matrix.repo }} demo-shop && cp -R docker-sdk demo-shop

      - name: Provide env variables
        run: |
          export SPRYKER_PLATFORM_IMAGE=${{ matrix.platform-image}}
          export PROGRESS_TYPE=plain
          export SPRYKER_CURRENT_REGION=EU
          export DYNAMIC_STORE_MODE=true

      - name: Prepare
        run: |
          cd ../demo-shop

      - uses: ramsey/composer-install@v3
        with:
          composer-options: "-q --ignore-platform-reqs --optimize-autoloader --no-interaction --prefer-install=auto"

      - name: Run
        run: |
          docker-sdk/sdk boot .github/deploy/deploy.ci.acceptance.mariadb.yml
          docker-sdk/sdk up -t

      - name: Run Acceptance Tests
        run: |
            docker-sdk/sdk testing codecept fixtures
            docker-sdk/sdk testing composer dump-autoload -o -a --apcu -q
            echo "console queue:worker:start --stop-when-empty"
            docker-sdk/sdk testing console queue:worker:start --stop-when-empty

      - name: Run API Tests
        run: |
          docker/sdk testing codecept run -c tests/codeception.api.yml
