# syntax = docker/dockerfile:1.5
#ARG SPRYKER_PLATFORM_IMAGE=spryker/php:7.3
ARG SPRYKER_DOCKER_SDK_CONTEXT_BUILD_IMAGE
ARG SPRYKER_APP_BUILD_IMAGE

FROM ${SPRYKER_APP_BUILD_IMAGE} as application-build

FROM ${SPRYKER_DOCKER_SDK_CONTEXT_BUILD_IMAGE} as docker-sdk-context-build

FROM oleg1628/docker-php:slim AS application-production
#FROM ${SPRYKER_PLATFORM_IMAGE} AS application-production

COPY --from=application-build /data /data
COPY --from=docker-sdk-context-build /usr/local/etc/php-fpm.d/worker.conf /usr/local/etc/php-fpm.d/worker.conf
COPY --from=docker-sdk-context-build /usr/local/etc/php/php.ini /usr/local/etc/php/php.ini
COPY --from=docker-sdk-context-build /usr/local/etc/php/conf.d/90-opcache.ini /usr/local/etc/php/conf.d/90-opcache.ini
COPY --from=docker-sdk-context-build /usr/local/etc/php/conf.d/99-from-deploy-yaml-php.ini /usr/local/etc/php/conf.d/99-from-deploy-yaml-php.ini
COPY --from=docker-sdk-context-build /home/spryker/build.php /home/spryker/build.php

# TBD: Not sure if it's only needed for build stage or also during application runtime. Clarify. If not used, then delete the block
ENV SPRYKER_IN_DOCKER=1
ENV COMPOSER_IGNORE_CHROMEDRIVER=1
{% for envName, envValue in _envs %}
ENV {{ envName }}='{{ envValue }}'
{% endfor %}

ARG SPRYKER_PIPELINE
ENV SPRYKER_PIPELINE=${SPRYKER_PIPELINE}
ARG APPLICATION_ENV
ARG SPRYKER_DB_ENGINE
ENV APPLICATION_ENV=${APPLICATION_ENV}
ENV SPRYKER_DB_ENGINE=${SPRYKER_DB_ENGINE}
#####


# Create log directory
ARG SPRYKER_LOG_DIRECTORY
ENV SPRYKER_LOG_DIRECTORY=${SPRYKER_LOG_DIRECTORY}
RUN mkdir -p ${SPRYKER_LOG_DIRECTORY} && \
chown spryker:spryker ${SPRYKER_LOG_DIRECTORY}

# Creates the list of known hosts
ARG KNOWN_HOSTS
RUN mkdir -p /home/spryker/.ssh && chmod 0700 /home/spryker/.ssh
RUN sh -c '[ ! -z "${KNOWN_HOSTS}" ] && ssh-keyscan -t rsa ${KNOWN_HOSTS} >> /home/spryker/.ssh/known_hosts || true'
RUN chown spryker:spryker -R /home/spryker/.ssh

# PHP-FPM environment variables
ENV PHP_FPM_PM=dynamic
ENV PHP_FPM_PM_MAX_CHILDREN=4
ENV PHP_FPM_PM_START_SERVERS=2
ENV PHP_FPM_PM_MIN_SPARE_SERVERS=1
ENV PHP_FPM_PM_MAX_SPARE_SERVERS=2
ENV PHP_FPM_PM_MAX_REQUESTS=500
ENV PHP_FPM_REQUEST_TERMINATE_TIMEOUT=1m

# removing default opcache.ini
RUN rm -f /usr/local/etc/php/conf.d/opcache.ini

{% if _phpExtensions is defined and _phpExtensions is not empty %}
{% for phpExtention in _phpExtensions %}
RUN mv /usr/local/etc/php/disabled/{{phpExtention}}.ini /usr/local/etc/php/conf.d/90-{{phpExtention}}.ini
{% endfor %}
{% endif %}

COPY --chown=spryker:spryker public ${srcRoot}/public
COPY --chown=spryker:spryker frontend ${srcRoot}/frontend
COPY --chown=spryker:spryker .yarn* ${srcRoot}/.yarn
# this command doesn't copy subdirectories as long as they don't have a dot in their name
COPY --chown=spryker:spryker .* *.* LICENSE ${srcRoot}/

USER root
RUN rm -rf /var/run/opcache/*
RUN chown -R spryker:spryker /home/spryker

ARG SPRYKER_BUILD_HASH='current'
ENV SPRYKER_BUILD_HASH=${SPRYKER_BUILD_HASH}
ARG SPRYKER_BUILD_STAMP=''
ENV SPRYKER_BUILD_STAMP=${SPRYKER_BUILD_STAMP}

CMD [ "php-fpm", "--nodaemonize" ]
EXPOSE 9000

